baseURL = 'https://gustavobuenoblog.netlify.app/'
languageCode = 'pt-br'
title = 'gustavo bueno blog'

paginate = 4

[params]
  description = "Blog sobre tecnologia e livros"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"